baseurl = "/"
title = "René Nauheimer"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = '<!--[-->Loving the Clouds. Promoting Soul. Spreading Smiles.<!--]--><br />
                <!--[-->Believes in team human and the magic of vivid communities. <a href="https://html5up.net/license">Read more</a>.<!--]-->'
  logoimage = "/images/rene.jpg"
  copyright = "Rene Nauheimer"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/rene_nauheimer"

[[params.social]]
  medium = "LinkedIn"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/ren%C3%A9-nauheimer-614233126/"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "https://instagram.com/renaui"

[[params.social]]
  medium = "medium"
  icon = "medium"
  link = "https://medium.com/@renaui"

[languages]
[languages.en]
languageName = "English"
weight = 1

[languages.de]
languageName = "Deutsch"
weight = 2
title = "René Nauheimer"
description = '<!--[-->A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<!--]--><br />
                <!--[-->for free under the <a href="https://html5up.net/license">Creative Commons</a> license.<!--]-->'

[languages.fr]
languageName = "Français"
weight = 3
title = "René Nauheimer"
description = '<!--[-->A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<!--]--><br />
                <!--[-->for free under the <a href="https://html5up.net/license">Creative Commons</a> license.<!--]-->'


[languages.br]
languageName = "Português"
weight = 4
title = "René Nauheimer"
description = '<!--[-->A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<!--]--><br />
                <!--[-->for free under the <a href="https://html5up.net/license">Creative Commons</a> license.<!--]-->'
